In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
spam_df = pd.read_csv('Downloads/spam.csv')

In [3]:
spam_df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
spam_df.sample(10)

Category                                            Message
442       ham             You were supposed to wake ME up &gt;:(
363       ham                    Check audrey's status right now
268      spam  Ur ringtone service has changed! 25 Free credi...
1300      ham  Great to hear you are settling well. So what's...
1177      ham  Did he say how fantastic I am by any chance, o...
2878      ham  twenty past five he said will this train have ...
508       ham  You should know now. So how's anthony. Are you...
2937      ham  And stop wondering "wow is she ever going to s...
3578      ham    Yeah confirmed for you staying at  that weekend
3144      ham  Boy; I love u Grl: Hogolo Boy: gold chain kods...

In [5]:
# inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
# turning spam/ham into numerical data,creating a new column called spam
spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x  == 'spam' else 0)

In [7]:
spam_df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [8]:
X_train,X_test,y_train,y_test = train_test_split(spam_df.Message,spam_df.spam , test_size=0.25)

In [9]:
X_train.describe()

count                       4179
unique                      3927
top       Sorry, I'll call later
freq                          25
Name: Message, dtype: object

In [10]:
# find word count and store data as matrix
cv = CountVectorizer()
X_train_count = cv.fit_transform(X_train.values)

In [11]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7476))

In [13]:
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [18]:
## pre-test ham
email_ham = ["hey wanna meet up for the game?"]
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [35]:
## pre test spam (word order dont matter )
email_spam = [" subscribe and join my telegram and get bonus and click on the prize"]
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [40]:
## test model
X_test_count = cv.transform(X_test)
model.score(X_test_count,y_test)

0.9806173725771715